# ローカル開発用postgresql
version: '3'

services:
  postgresql:
    image: postgres:15.3
    # restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: